secret: 'admin' # CHANGE-ME: api访问密码
log-level: debug
bind-address: "*"
allow-lan: true
ipv6: true
profile:
  store-selected: true
  store-fake-ip: true
external-controller: :9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.tar.gz"
geodata-loader: standard
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
mode: direct
unified-delay: true
tcp-concurrent: true
client-fingerprint: random
mixed-port: 7890 # HTTP(S) 和 SOCKS5 代理混合端口
listeners:
  - name: anytls-in
    type: anytls
    port: 14443
    listen: 0.0.0.0
    password: CHANGE-ME

  - name: ss-in
    type: shadowsocks
    port: 14445
    listen: 0.0.0.0
    cipher: chacha20-ietf-poly1305
    password: CHANGE-ME
    udp: true
tun:
  enable: false
dns:
  enable: false
