services:
  mihomo:
    image: metacubex/mihomo:latest
    container_name: mihomo
    hostname: mihomo
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./:/root/.config/mihomo
